config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/google_oauth2', to: 'sessions#omniauth'
  
  get '/auth/:provider/callback' => 'sessions#create'

  resources :reviews
  resources :coffees do
    resources :reviews, only: [:new, :index]
  end
  
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :coffees
    validates :brand_name, presence: true, uniqueness: true

    scope :alpha, -> {reorder(:brand_name)}
end

app/models/coffee.rb
class Coffee < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews
  accepts_nested_attributes_for :brand

  validates :name, presence: true
  validate :not_a_duplicate

  scope :order_by_score, -> {left_joins(:reviews).group(:id).order('avg(score) desc')}

  def self.alpha
    order(:name)
  end

  def brand_attributes=(attributes)
    self.brand = Brand.find_or_create_by(attributes) if !attributes['brand_name'].empty?
    self.brand
  end

  def not_a_duplicate
    coffee = Coffee.find_by(name: name, brand_id: brand_id)
    if !!coffee && coffee != self
      errors.add(:name, 'already added')
    end
  end

  # def coffee_brand_name
  #   brand.try(:brand_name)
  # end

  def name_and_brand_name
    "#{name} - #{brand.try(:brand_name)}"
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :coffee

  validates :title, presence: true
  validates :score, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}


  validates :coffee, uniqueness: { scope: :user, message: "You have already reviewed this coffee."  }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :reviewed_coffees, through: :reviews, source: :coffee

    has_many :coffees

    validates :username, uniqueness: true, presence: true
    validates :email, uniqueness: true

    has_secure_password

    def self.from_omniauth(auth)
      byebug
      self.find_or_create_by(username: auth[:info][:email]) do |u|
        u.password = SecureRandom.hex
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
  
    private
  
    def logged_in?
      !!session[:user_id]
    end
  
    def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
  
    def redirect_if_not_logged_in
      redirect_to login_path if !logged_in?
    end
  
  
  end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @brands = Brand.all
    end
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
    before_action :set_coffee, only:[:show, :edit, :update]
    before_action :redirect_if_not_logged_in

    def new
        @coffee = Coffee.new
        @coffee.build_brand
    end

    def create
        @coffee = Coffee.new(coffee_params)
        @coffee.user_id = session[:user_id]
        if @coffee.save
            redirect_to coffee_path(@coffee)
        else
            @coffee.build_brand
            render :new
        end
    end

    def index
        @coffees = Coffee.order_by_score.includes(:brand_name)
    end

    def show
        # @coffee = Coffee.find_by_id(params[:id])
    end

    def edit
    end

    def update
        if @coffee.update(coffee_params)
            redirect_to coffee_path(@coffee)
        else
            render :edit
        end
    end

    private

    def coffee_params
      params.require(:coffee).permit(:name, :roast_type, :description, :brand_id, brand_attributes: [:brand_name])
    end

    def set_coffee
        @coffee = Coffee.find_by(params[:id])
        redirect_to coffee_path if !@coffee
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :redirect_if_not_logged_in

    def new
        if @coffee = Coffee.find_by_id(params[:coffee_id])
          @review = @coffee.reviews.build
        else
          @review = Review.new
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
          redirect_to review_path(@review)
        else
          render :new
        end
    end

    def show
        @review = Review.find_by_id(params[:id])
    end
    
    def index
      #validate if nested
        if @coffee = Coffee.find_by_id(params[:coffee_id])
          #nested 
          @reviews = @coffee.reviews
        else
          #not nested
            @reviews = Review.all
        end
    end

    private

    def review_params
        params.require(:review).permit(:coffee_id, :score, :title, :content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    def new
    end

    def create
      user = User.find_by(email: params[:user][:email])
      if user && user.authenticate(params[:user][:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash[:message] = ["Invalid login. Please try again"]
        redirect_to login_path
      end
    end
    

      def omniauth
        @user = User.from_omniauth(auth)
        @user.save
        session[:user_id] = @user.id
      redirect_to user_path(@user)
    end

  private

    def auth
      request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          # byebug
          render :new
        end
      end

      def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        # byebug
        redirect_to '/' if !@user
      end

      private
      def user_params
        params.require(:user).permit(:username, :email, :password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def render_nav_bar
      if logged_in?
        render partial: 'layouts/loggedin'
      else
        render partial: 'layouts/loggedout'
      end
    end
  end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def display_header(review)
      if params[:coffee_id]
          content_tag(:h1, "Add a review for #{review.coffee.name} -  #{review.coffee.brand.brand_name}")
      else
        content_tag(:h1, "Create review")
      end
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/index.html.erb
<h1>All the Brands</h1>

<ol>
  <% @brands.each do |brand| %>
    <li><%= brand.brand_name%></li>
  <% end %>
</ol>

app/views/coffees/_form.html.erb
<%= render partial: "layouts/errors"  %>
<% form_for(@coffee) do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :roast_type %>
    <%= f.text_field :roast_type %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
 

  <p> Select an existing brand: </p>
  <div>
    <%= f.collection_select :brand_id, Brand.all, :id, :brand_name, include_blank: 'Select brand'%>

  </div>

  <p> Or add a new brand: </p>
  <div>
    <%=f.fields_for :brand do |b| %>
      <%= b.label :brand_name %>
      <%= b.text_field :brand_name %>
    <% end %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/coffees/edit.html.erb
<h1>Edit coffee</h1>



<%= render partial: 'form'%>

app/views/coffees/index.html.erb
<h1>All coffees</h1>

<% @coffees.each do |c| %>

  <h2><%= link_to c.name, coffee_path(c.id)%> - <%= c.brand.brand_name %> </h2>
  <%= link_to "Add a review", new_coffee_review_path%>
  <% end %>
  <div>
    <p><%= c.description %></p>
  </div>

app/views/coffees/new.html.erb
<h1>Add a new coffee</h1>



<%= render 'form' %>

app/views/coffees/show.html.erb
<h1><%= @coffee.name%>  </h1>


<h2> <%= @coffee.brand_name %> </h2>
<div>
  <p><%= @coffee.description %></p>
</div>

<h3>Added by: <%= link_to @coffee.user, user_path(@user)%> </h3>

<%= link_to "Edit #{@coffee.flavor}", edit_coffee_path(@coffee) if @coffee.user == current_user%>

<br></br>

<%= link_to "Show all reviews", coffee_reviews_path(@coffee) %>

app/views/layouts/_errors.html.erb
<% if object_id.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prevented this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin.html.erb
<%= link_to "Log Out", logout_path, method: :delete %> |
<%= link_to "Add a Coffee", new_coffee_path %> |
<%= link_to "All Coffees", coffee_path(:id) %> |
<%= link_to "Add a Review", new_review_path %> |
<%= link_to "All Reviews", reviews_path %> |

<%= link_to "Home", user_path(current_user)%>

app/views/layouts/_loggedout.html.erb
<%= link_to "Login", login_path %> |
<%= link_to "Signup", signup_path %> |
<%= link_to "Sign in with Google", "/auth/google_oauth2/callback" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <div><%= render_nav_bar %></div>
 
   <body>
     <%= yield %>
   </body>
 </html>

app/views/reviews/index.html.erb
<% if @coffee %>
  <h1>Reviews for <%= @coffee.name%> - <%= @coffee.brand_name%></h1>
<% else %>
  <h1>All reviews </h1>
<% end %>

<ul>
<% @reviews.each do |review| %>

  <li>
    <%= @review.coffee.name%>: <%= link_to @review.title, review_path(review)%> - <%= @review.score%>
  </li> <br>

<% end %>
</ul>

app/views/reviews/new.html.erb
<%=  display_header(@review)%>
<%= render partial: 'layouts/errors' %>

<%= form_for(@review) do |f| %>
    <% if params[:coffee_id] %>
        <%= f.hidden_field :coffee_id %>
    <% else %>
    <div>
    <%= f.label :coffee_id, "Select a coffee" %>
    <%= f.collection_select :coffee_id, Coffee.alpha, :id, :name_and_brand_name, include_blank: true %>
  </div>
<% end %>
    <div>
        <%= f.label :score %>
        <%= f.number_field :score, min:0, max:10 %>
    </div>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content, size: "30x10" %>
        </div>
        <br>
      
        <%= f.submit %>
      <% end %>

app/views/reviews/show.html.erb
<h1><%= @review.title%> - <%= @review.score%> </h1>

<p><%= @review.content%></p>

app/views/users/new.html.erb
<h1>Sign up below:</h1>

<%= form_for @user, url: signup_path do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :email %>
  <%= f.email_field :email %><br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username%></h1>

<h3>Coffees reviewed by <%=@user.username%>:</h3>
<ul>
  <% @user.reviewed_coffees.each do |ic|%>
  <li> <%= link_to c.name_and_brand_name, coffee_path(c)%> </li>
  <% end %>
</ul>